# Generated by Django 5.1.1 on 2024-09-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='baner',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
